// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinistryOfJustice.Models;

namespace MinistryOfJustice.Migrations
{
    [DbContext(typeof(MinistryOfJusticeContext))]
    [Migration("20210621192601_DB")]
    partial class DB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinistryOfJustice.Models.Association", b =>
                {
                    b.Property<int>("AssociationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AssociationTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConversionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("DonationAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonationPurpose")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DonationTerms")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AssociationId");

                    b.HasIndex("AssociationTypeId");

                    b.HasIndex("CurrencyTypeId");

                    b.ToTable("Associations");

                    b.HasData(
                        new
                        {
                            AssociationId = 1,
                            AssociationTypeId = 1,
                            ConversionRate = 1.1m,
                            CreatedByUserId = 1,
                            CurrencyTypeId = 1,
                            DonationAmount = 9000m,
                            DonationPurpose = "מטרה 1",
                            DonationTerms = "חוקים",
                            Name = "עמותה 1"
                        },
                        new
                        {
                            AssociationId = 2,
                            AssociationTypeId = 2,
                            ConversionRate = 4.5m,
                            CreatedByUserId = 2,
                            CurrencyTypeId = 2,
                            DonationAmount = 8000m,
                            DonationPurpose = "מטרה 2",
                            DonationTerms = "חוקים",
                            Name = "עמותה 2"
                        });
                });

            modelBuilder.Entity("MinistryOfJustice.Models.AssociationType", b =>
                {
                    b.Property<int>("AssociationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AssociationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssociationTypeId");

                    b.ToTable("AssociationTypes");

                    b.HasData(
                        new
                        {
                            AssociationTypeId = 1,
                            AssociationTypeName = "סוג 1"
                        },
                        new
                        {
                            AssociationTypeId = 2,
                            AssociationTypeName = "סוג 2"
                        },
                        new
                        {
                            AssociationTypeId = 3,
                            AssociationTypeName = "סוג 3"
                        });
                });

            modelBuilder.Entity("MinistryOfJustice.Models.CurrencyType", b =>
                {
                    b.Property<int>("CurrencyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurrencyTypeId");

                    b.ToTable("CurrencyTypes");

                    b.HasData(
                        new
                        {
                            CurrencyTypeId = 1,
                            CurrencyTypeName = "סוג 1"
                        },
                        new
                        {
                            CurrencyTypeId = 2,
                            CurrencyTypeName = "סוג 2"
                        },
                        new
                        {
                            CurrencyTypeId = 3,
                            CurrencyTypeName = "סוג 3"
                        });
                });

            modelBuilder.Entity("MinistryOfJustice.Models.Association", b =>
                {
                    b.HasOne("MinistryOfJustice.Models.AssociationType", "AssociationType")
                        .WithMany()
                        .HasForeignKey("AssociationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinistryOfJustice.Models.CurrencyType", "CurrencyType")
                        .WithMany()
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociationType");

                    b.Navigation("CurrencyType");
                });
#pragma warning restore 612, 618
        }
    }
}
